spring.application.name=sb-ecomm

project.image=images/

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:4688065e-abd7-4357-8c66-c20616592bc0
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.properties.format_sql=true
spring.jpa.hibernate.ddl-auto=update

spring.app.jwtSecret=c0f85991d11d5544fd872506c3cb0b98831afe9dca1a4fa4a6fc9b1f32712ae0
spring.app.jwtExpirationMs=3000000

logging.level.org.springframework=DEBUG
logging.level.com.ecomm=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.ecommerce.sb_ecomm=DEBUG
